package com.gda.cotizador.dto.db;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Getter
@Setter
public class CConvenioDto {

	private Integer cconvenio;
    private String sconvenio;
    private Date dregistro;
    private Integer ctipoconvenio;
    private Integer ccliente;
    private Integer czonaventa;
    private Integer user_id;
    private Integer user_id_change;
    private String spassword;
    private String spasswordconsulta;
    private String scorreoelectronico;
    private Integer erpuenvioconvenio;
    private BigDecimal mventasenero2016;
    private BigDecimal mfacturadoenero2016;
    private BigDecimal mfacturadosinordenesenero2016;
    private BigDecimal mcobradoenero2016;
    private BigDecimal mcobradosinordenesenero2016;
    private BigDecimal uordenesenero2016;
    private BigDecimal uordenessinfacturaenero2016;
    private BigDecimal mventasfebrero2016;
    private BigDecimal mfacturadofebrero2016;
    private BigDecimal mfacturadosinordenesfebrero2016;
    private BigDecimal mcobradofebrero2016;
    private BigDecimal mcobradosinordenesfebrero2016;
    private BigDecimal uordenesfebrero2016;
    private BigDecimal uordenessinfacturafebrero2016;
    private BigDecimal mventasmarzo2016;
    private BigDecimal mfacturadomarzo2016;
    private BigDecimal mfacturadosinordenesmarzo2016;
    private BigDecimal mcobradomarzo2016;
    private BigDecimal mcobradosinordenesmarzo2016;
    private BigDecimal uordenesmarzo2016;
    private BigDecimal uordenessinfacturamarzo2016;
    private BigDecimal mventasabril2016;
    private BigDecimal mfacturadoabril2016;
    private BigDecimal mfacturadosinordenesabril2016;
    private BigDecimal mcobradoabril2016;
    private BigDecimal mcobradosinordenesabril2016;
    private BigDecimal uordenesabril2016;
    private BigDecimal uordenessinfacturaabril2016;
    private BigDecimal mventasmayo2016;
    private BigDecimal mfacturadomayo2016;
    private BigDecimal mfacturadosinordenesmayo2016;
    private BigDecimal mcobradomayo2016;
    private BigDecimal mcobradosinordenesmayo2016;
    private BigDecimal uordenesmayo2016;
    private BigDecimal uordenessinfacturamayo2016;
    private BigDecimal mventasjunio2016;
    private BigDecimal mfacturadojunio2016;
    private BigDecimal mfacturadosinordenesjunio2016;
    private BigDecimal mcobradojunio2016;
    private BigDecimal mcobradosinordenesjunio2016;
    private BigDecimal uordenesjunio2016;
    private BigDecimal uordenessinfacturajunio2016;
    private BigDecimal mventasjulio2016;
    private BigDecimal mfacturadojulio2016;
    private BigDecimal mfacturadosinordenesjulio2016;
    private BigDecimal mcobradojulio2016;
    private BigDecimal mcobradosinordenesjulio2016;
    private BigDecimal uordenesjulio2016;
    private BigDecimal uordenessinfacturajulio2016;
    private BigDecimal mventasagosto2016;
    private BigDecimal mfacturadoagosto2016;
    private BigDecimal mfacturadosinordenesagosto2016;
    private BigDecimal mcobradoagosto2016;
    private BigDecimal mcobradosinordenesagosto2016;
    private BigDecimal uordenesagosto2016;
    private BigDecimal uordenessinfacturaagosto2016;
    private BigDecimal mventasseptiembre2016;
    private BigDecimal mfacturadoseptiembre2016;
    private BigDecimal mfacturadosinordenesseptiembre2016;
    private BigDecimal mcobradoseptiembre2016;
    private BigDecimal mcobradosinordenesseptiembre2016;
    private BigDecimal uordenesseptiembre2016;
    private BigDecimal uordenessinfacturaseptiembre2016;
    private BigDecimal mventasoctubre2016;
    private BigDecimal mfacturadooctubre2016;
    private BigDecimal mfacturadosinordenesoctubre2016;
    private BigDecimal mcobradooctubre2016;
    private BigDecimal mcobradosinordenesoctubre2016;
    private BigDecimal uordenesoctubre2016;
    private BigDecimal uordenessinfacturaoctubre2016;
    private BigDecimal mventasnoviembre2016;
    private BigDecimal mfacturadonoviembre2016;
    private BigDecimal mfacturadosinordenesnoviembre2016;
    private BigDecimal mcobradonoviembre2016;
    private BigDecimal mcobradosinordenesnoviembre2016;
    private BigDecimal uordenesnoviembre2016;
    private BigDecimal uordenessinfacturanoviembre2016;
    private BigDecimal mventasdiciembre2016;
    private BigDecimal mfacturadodiciembre2016;
    private BigDecimal mfacturadosinordenesdiciembre2016;
    private BigDecimal mcobradodiciembre2016;
    private BigDecimal mcobradosinordenesdiciembre2016;
    private BigDecimal uordenesdiciembre2016;
    private BigDecimal uordenessinfacturadiciembre2016;
    private Integer cagrupacion;
    private Integer cconveniosinonimo;
    private String sconveniosinonimo;
    private Integer ccanalconvenio;
    private String ssucursal;
    private String ssucursalcotizacion;
    private Boolean blunes;
    private Boolean bmartes;
    private Boolean bmiercoles;
    private Boolean bjueves;
    private Boolean bviernes;
    private Boolean bsabado;
    private Boolean bdomingo;
    private Integer uhorainicio;
    private Integer uhoratermino;
    private Integer uedadinicio;
    private Integer uedadtermino;
    private String sdireccionfiscalemisor;
    private String semailresultados;
    private Boolean bdespliegadomicilio;
    private Integer cconveniorelacionado;
		
}
