package com.gda.cotizador.dao.mapper.db;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.gda.cotizador.dto.db.CConvenioDto;

public class CConvenioMapper implements RowMapper<CConvenioDto>{

	@Override
	public CConvenioDto mapRow(ResultSet rs, int rowNum) throws SQLException {
		CConvenioDto dto = new CConvenioDto();
		dto.setCconvenio(rs.getInt("cconvenio"));
		dto.setSconvenio(rs.getString("sconvenio"));
		dto.setDregistro(rs.getTimestamp("dregistro"));
		dto.setCtipoconvenio(rs.getInt("ctipoconvenio"));
		dto.setCcliente(rs.getInt("ccliente"));
		dto.setCzonaventa(rs.getInt("czonaventa"));
		dto.setUser_id(rs.getInt("user_id"));
		dto.setUser_id_change(rs.getInt("user_id_change"));
		dto.setSpassword(rs.getString("spassword"));
		dto.setSpasswordconsulta(rs.getString("spasswordconsulta"));
		dto.setScorreoelectronico(rs.getString("scorreoelectronico"));
		dto.setErpuenvioconvenio(rs.getInt("erpuenvioconvenio"));
		dto.setMventasenero2016(rs.getBigDecimal("mventasenero2016"));
		dto.setMfacturadoenero2016(rs.getBigDecimal("mfacturadoenero2016"));
		dto.setMfacturadosinordenesenero2016(rs.getBigDecimal("mfacturadosinordenesenero2016"));
		dto.setMcobradoenero2016(rs.getBigDecimal("mcobradoenero2016"));
		dto.setMcobradosinordenesenero2016(rs.getBigDecimal("mcobradosinordenesenero2016"));
		dto.setUordenesenero2016(rs.getBigDecimal("uordenesenero2016"));
		dto.setUordenessinfacturaenero2016(rs.getBigDecimal("uordenessinfacturaenero2016"));
		dto.setMventasfebrero2016(rs.getBigDecimal("mventasfebrero2016"));
		dto.setMfacturadofebrero2016(rs.getBigDecimal("mfacturadofebrero2016"));
		dto.setMfacturadosinordenesfebrero2016(rs.getBigDecimal("mfacturadosinordenesfebrero2016"));
		dto.setMcobradofebrero2016(rs.getBigDecimal("mcobradofebrero2016"));
		dto.setMcobradosinordenesfebrero2016(rs.getBigDecimal("mcobradosinordenesfebrero2016"));
		dto.setUordenesfebrero2016(rs.getBigDecimal("uordenesfebrero2016"));
		dto.setUordenessinfacturafebrero2016(rs.getBigDecimal("uordenessinfacturafebrero2016"));
		dto.setMventasmarzo2016(rs.getBigDecimal("mventasmarzo2016"));
		dto.setMfacturadomarzo2016(rs.getBigDecimal("mfacturadomarzo2016"));
		dto.setMfacturadosinordenesmarzo2016(rs.getBigDecimal("mfacturadosinordenesmarzo2016"));
		dto.setMcobradomarzo2016(rs.getBigDecimal("mcobradomarzo2016"));
		dto.setMcobradosinordenesmarzo2016(rs.getBigDecimal("mcobradosinordenesmarzo2016"));
		dto.setUordenesmarzo2016(rs.getBigDecimal("uordenesmarzo2016"));
		dto.setUordenessinfacturamarzo2016(rs.getBigDecimal("uordenessinfacturamarzo2016"));
		dto.setMventasabril2016(rs.getBigDecimal("mventasabril2016"));
		dto.setMfacturadoabril2016(rs.getBigDecimal("mfacturadoabril2016"));
		dto.setMfacturadosinordenesabril2016(rs.getBigDecimal("mfacturadosinordenesabril2016"));
		dto.setMcobradoabril2016(rs.getBigDecimal("mcobradoabril2016"));
		dto.setMcobradosinordenesabril2016(rs.getBigDecimal("mcobradosinordenesabril2016"));
		dto.setUordenesabril2016(rs.getBigDecimal("uordenesabril2016"));
		dto.setUordenessinfacturaabril2016(rs.getBigDecimal("uordenessinfacturaabril2016"));
		dto.setMventasmayo2016(rs.getBigDecimal("mventasmayo2016"));
		dto.setMfacturadomayo2016(rs.getBigDecimal("mfacturadomayo2016"));
		dto.setMfacturadosinordenesmayo2016(rs.getBigDecimal("mfacturadosinordenesmayo2016"));
		dto.setMcobradomayo2016(rs.getBigDecimal("mcobradomayo2016"));
		dto.setMcobradosinordenesmayo2016(rs.getBigDecimal("mcobradosinordenesmayo2016"));
		dto.setUordenesmayo2016(rs.getBigDecimal("uordenesmayo2016"));
		dto.setUordenessinfacturamayo2016(rs.getBigDecimal("uordenessinfacturamayo2016"));
		dto.setMventasjunio2016(rs.getBigDecimal("mventasjunio2016"));
		dto.setMfacturadojunio2016(rs.getBigDecimal("mfacturadojunio2016"));
		dto.setMfacturadosinordenesjunio2016(rs.getBigDecimal("mfacturadosinordenesjunio2016"));
		dto.setMcobradojunio2016(rs.getBigDecimal("mcobradojunio2016"));
		dto.setMcobradosinordenesjunio2016(rs.getBigDecimal("mcobradosinordenesjunio2016"));
		dto.setUordenesjunio2016(rs.getBigDecimal("uordenesjunio2016"));
		dto.setUordenessinfacturajunio2016(rs.getBigDecimal("uordenessinfacturajunio2016"));		
		dto.setMventasjulio2016(rs.getBigDecimal("mventasjulio2016"));
		dto.setMfacturadojulio2016(rs.getBigDecimal("mfacturadojulio2016"));
		dto.setMfacturadosinordenesjulio2016(rs.getBigDecimal("mfacturadosinordenesjulio2016"));
		dto.setMcobradojulio2016(rs.getBigDecimal("mcobradojulio2016"));
		dto.setMcobradosinordenesjulio2016(rs.getBigDecimal("mcobradosinordenesjulio2016"));
		dto.setUordenesjulio2016(rs.getBigDecimal("uordenesjulio2016"));
		dto.setUordenessinfacturajulio2016(rs.getBigDecimal("uordenessinfacturajulio2016"));		
		dto.setMventasagosto2016(rs.getBigDecimal("mventasagosto2016"));
		dto.setMfacturadoagosto2016(rs.getBigDecimal("mfacturadoagosto2016"));
		dto.setMfacturadosinordenesagosto2016(rs.getBigDecimal("mfacturadosinordenesagosto2016"));
		dto.setMcobradoagosto2016(rs.getBigDecimal("mcobradoagosto2016"));
		dto.setMcobradosinordenesagosto2016(rs.getBigDecimal("mcobradosinordenesagosto2016"));
		dto.setUordenesagosto2016(rs.getBigDecimal("uordenesagosto2016"));
		dto.setUordenessinfacturaagosto2016(rs.getBigDecimal("uordenessinfacturaagosto2016"));		
		dto.setMventasseptiembre2016(rs.getBigDecimal("mventasseptiembre2016"));
		dto.setMfacturadoseptiembre2016(rs.getBigDecimal("mfacturadoseptiembre2016"));
		dto.setMfacturadosinordenesseptiembre2016(rs.getBigDecimal("mfacturadosinordenesseptiembre2016"));
		dto.setMcobradoseptiembre2016(rs.getBigDecimal("mcobradoseptiembre2016"));
		dto.setMcobradosinordenesseptiembre2016(rs.getBigDecimal("mcobradosinordenesseptiembre2016"));
		dto.setUordenesseptiembre2016(rs.getBigDecimal("uordenesseptiembre2016"));
		dto.setUordenessinfacturaseptiembre2016(rs.getBigDecimal("uordenessinfacturaseptiembre2016"));		
		dto.setMventasoctubre2016(rs.getBigDecimal("mventasoctubre2016"));
		dto.setMfacturadooctubre2016(rs.getBigDecimal("mfacturadooctubre2016"));
		dto.setMfacturadosinordenesoctubre2016(rs.getBigDecimal("mfacturadosinordenesoctubre2016"));
		dto.setMcobradooctubre2016(rs.getBigDecimal("mcobradooctubre2016"));
		dto.setMcobradosinordenesoctubre2016(rs.getBigDecimal("mcobradosinordenesoctubre2016"));
		dto.setUordenesoctubre2016(rs.getBigDecimal("uordenesoctubre2016"));
		dto.setUordenessinfacturaoctubre2016(rs.getBigDecimal("uordenessinfacturaoctubre2016"));		
		dto.setMventasnoviembre2016(rs.getBigDecimal("mventasnoviembre2016"));
		dto.setMfacturadonoviembre2016(rs.getBigDecimal("mfacturadonoviembre2016"));
		dto.setMfacturadosinordenesnoviembre2016(rs.getBigDecimal("mfacturadosinordenesnoviembre2016"));
		dto.setMcobradonoviembre2016(rs.getBigDecimal("mcobradonoviembre2016"));
		dto.setMcobradosinordenesnoviembre2016(rs.getBigDecimal("mcobradosinordenesnoviembre2016"));
		dto.setUordenesnoviembre2016(rs.getBigDecimal("uordenesnoviembre2016"));
		dto.setUordenessinfacturanoviembre2016(rs.getBigDecimal("uordenessinfacturanoviembre2016"));		
		dto.setMventasdiciembre2016(rs.getBigDecimal("mventasdiciembre2016"));
		dto.setMfacturadodiciembre2016(rs.getBigDecimal("mfacturadodiciembre2016"));
		dto.setMfacturadosinordenesdiciembre2016(rs.getBigDecimal("mfacturadosinordenesdiciembre2016"));
		dto.setMcobradodiciembre2016(rs.getBigDecimal("mcobradodiciembre2016"));
		dto.setMcobradosinordenesdiciembre2016(rs.getBigDecimal("mcobradosinordenesdiciembre2016"));
		dto.setUordenesdiciembre2016(rs.getBigDecimal("uordenesdiciembre2016"));
		dto.setUordenessinfacturadiciembre2016(rs.getBigDecimal("uordenessinfacturadiciembre2016"));
		dto.setCagrupacion(rs.getInt("cagrupacion"));
		dto.setCconveniosinonimo(rs.getInt("cconveniosinonimo"));
		dto.setSconveniosinonimo(rs.getString("sconveniosinonimo"));
		dto.setCcanalconvenio(rs.getInt("ccanalconvenio"));
		dto.setSsucursal(rs.getString("ssucursal"));
		dto.setSsucursalcotizacion(rs.getString("ssucursalcotizacion"));
		dto.setBlunes(rs.getBoolean("blunes"));
		dto.setBmartes(rs.getBoolean("bmartes"));
		dto.setBmiercoles(rs.getBoolean("bmiercoles"));
		dto.setBjueves(rs.getBoolean("bjueves"));
		dto.setBviernes(rs.getBoolean("bviernes"));
		dto.setBsabado(rs.getBoolean("bsabado"));
		dto.setBdomingo(rs.getBoolean("bdomingo"));
		dto.setUhorainicio(rs.getInt("uhorainicio"));
		dto.setUhoratermino(rs.getInt("uhoratermino"));
		dto.setUedadinicio(rs.getInt("uedadinicio"));
		dto.setUedadtermino(rs.getInt("uedadtermino"));
		dto.setSdireccionfiscalemisor(rs.getString("sdireccionfiscalemisor"));
		dto.setSemailresultados(rs.getString("semailresultados"));
		dto.setBdespliegadomicilio(rs.getBoolean("bdespliegadomicilio"));
		dto.setCconveniorelacionado(rs.getInt("cconveniorelacionado"));		
		return dto;
	}

}
